# Welcome to Secure Code Game Season-2/Level-1!

# Follow the instructions below to get started:

# Due to the nature of GitHub Actions, please find this level's vulnerable code inside:
# .github/workflows/jarvis-code.yml

# That is by navigating to:
#     .github/
#             > workflows/
#                         > jarvis-code.yml

name: Jarvis Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/
        
    - name: Publish results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d @results.json https://example.com/api/results
